club.index:
   path: /{_locale}/club
   controller: App\Controller\ClubController::index

club.add:
   path: /{_locale}/club/add
   controller: App\Controller\ClubController::add
   
club.show:
   path: /{_locale}/club/{club}
   controller: App\Controller\ClubController::show

club.add.affiliate:
   path: /{_locale}/club/{club}/addAffiliate
   controller: App\Controller\ClubController::addAffiliateMember