#index:
#    path: /
#    controller: App\Controller\DefaultController::index
logout:
    path: /logout
    
core.index:
   path: /
   controller: App\Controller\CoreController::index

post.index:
   path: /post
   controller: App\Controller\PostController::index  
