#index:
#    path: /
#    controller: App\Controller\DefaultController::index

homepage:
    path: /{_locale}
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    requirements:
        _locale: '%app_locales%'
    defaults:
        template: default/homepage.html.twig
        _locale: '%locale%'

logout:
    path: /logout
    
core.index:
   path: /
   controller: App\Controller\CoreController::index

post.index:
   path: /post
   controller: App\Controller\PostController::index  
